- name: Create an EC2 key
  ec2_key:
    name: "{{ project_name }}-{{ env }}-key"
    region: "{{ region }}"
  register: ec2_key

- name: Save private key
  copy: content="{{ ec2_key.key.private_key }}" dest="../aws-private.pem" mode=0600
  when: ec2_key.changed

- name: Create an Ec2 instance
  ec2:
      key_name: "{{ project_name }}-{{ env }}-key"
      group: defaults_ec2
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: true
      region: "{{ region }}"
      count: 1
      count_tag:
         Name: dev_project
      instance_tags:
         Name: dev_project
      vpc_subnet_id: subnet-070f1563
      assign_public_ip: yes
  register: ec2

- name: Add the new created EC2 instance to the local host group
  local_action: lineinfile 
      dest="./hosts" 
      regexp={{ item.public_ip }} 
      insertafter="[webserver]" 
      line="{{ item.public_ip }} {{ hoststring }}"
  with_items: "{{ ec2.instances }}"


- name: Wait for SSH to come up
  local_action: wait_for 
      host={{ item.public_ip }} 
      port=22 
      state=started
  with_items: "{{ ec2.instances }}"

